export const areasData = {
  oakland: {
    city: 'Oakland',
    slug: 'oakland',
    state: 'CA',
    zip: '94601',
    image: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=1600&q=80',
    metaTitle: 'Plumber in Oakland CA | 24/7 Emergency Plumbing | (510) 555-0199',
    metaDesc: 'Licensed plumbers in Oakland, CA. 24/7 emergency plumbing, drain cleaning, water heater repair & more. 30-minute response guaranteed. Call (510) 555-0199.',
    headline: 'Expert Plumbing Services in Oakland, CA',
    subtitle: 'Oakland\'s most trusted licensed plumbers — available 24/7 with a guaranteed 30-minute emergency response.',
    about: 'Oakland Plumbing Experts is headquartered right here in Oakland, CA. We\'ve been serving Oakland homeowners and businesses for over 15 years, from Rockridge and Temescal to East Oakland and the Fruitvale District. Our local knowledge means faster response times and a deep understanding of Oakland\'s older plumbing infrastructure — including the galvanized pipes and clay sewer lines common in homes built before 1970.',
    neighborhoods: ['Rockridge', 'Temescal', 'Fruitvale', 'East Oakland', 'Grand Lake', 'Montclair', 'Jack London Square', 'Uptown'],
    faqs: [
      { q: 'How fast can you reach me in Oakland?', a: 'We guarantee arrival within 30 minutes for emergencies anywhere in Oakland. Our trucks are stationed throughout the city for maximum coverage.' },
      { q: 'Do you serve all Oakland neighborhoods?', a: 'Yes — we cover every Oakland neighborhood including Rockridge, Temescal, Fruitvale, East Oakland, Grand Lake, Montclair, and all areas in between.' },
      { q: 'Are you licensed to work in Oakland?', a: 'Absolutely. We are fully licensed by the State of California and comply with all City of Oakland plumbing codes and permit requirements.' },
    ],
  },

  berkeley: {
    city: 'Berkeley',
    slug: 'berkeley',
    state: 'CA',
    zip: '94710',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=80',
    metaTitle: 'Plumber in Berkeley CA | Same-Day Service | (510) 555-0199',
    metaDesc: 'Expert plumbing services in Berkeley, CA. Emergency plumbing, drain cleaning, water heater repair. Same-day service available. Call (510) 555-0199.',
    headline: 'Professional Plumbing Services in Berkeley, CA',
    subtitle: 'Fast, reliable plumbing for Berkeley homes and businesses — licensed, insured, and available around the clock.',
    about: 'Oakland Plumbing Experts proudly serves all of Berkeley, CA — from the Berkeley Hills to the Flatlands and the UC Berkeley campus area. Berkeley\'s mix of historic craftsman homes and modern buildings means a wide variety of plumbing systems, and our experienced plumbers are equipped to handle them all. We understand Berkeley\'s unique plumbing challenges, including aging cast iron pipes in older homes and the high water pressure common in hillside properties.',
    neighborhoods: ['Berkeley Hills', 'Elmwood', 'Northside', 'Southside', 'West Berkeley', 'Downtown Berkeley', 'Claremont', 'Thousand Oaks'],
    faqs: [
      { q: 'Do you serve all of Berkeley, CA?', a: 'Yes. We cover all Berkeley neighborhoods including the Hills, Elmwood, Northside, Southside, West Berkeley, and the downtown area.' },
      { q: 'How quickly can you respond to a plumbing emergency in Berkeley?', a: 'We typically arrive within 30–40 minutes for Berkeley emergencies. Our Oakland base puts us just minutes away from most Berkeley locations.' },
      { q: 'Do you handle plumbing for older Berkeley homes?', a: 'Absolutely. We specialize in older plumbing systems common in Berkeley\'s historic homes, including cast iron drain lines, galvanized supply pipes, and clay sewer laterals.' },
    ],
  },

  alameda: {
    city: 'Alameda',
    slug: 'alameda',
    state: 'CA',
    zip: '94501',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&q=80',
    metaTitle: 'Plumber in Alameda CA | 24/7 Emergency Service | (510) 555-0199',
    metaDesc: 'Trusted plumbing services in Alameda, CA. Emergency plumbing, drain cleaning, sewer repair & more. Licensed & insured. Call (510) 555-0199.',
    headline: 'Trusted Plumbing Services in Alameda, CA',
    subtitle: 'Island-wide plumbing coverage for Alameda homes and businesses — fast response, upfront pricing, licensed plumbers.',
    about: 'Serving the entire island of Alameda, CA, Oakland Plumbing Experts understands the unique plumbing needs of this coastal community. Alameda\'s older Victorian and Craftsman homes often have aging plumbing infrastructure that requires experienced hands. Our proximity to Alameda via the Posey and Webster tubes means we can reach you quickly for any plumbing emergency, from the West End to Bay Farm Island.',
    neighborhoods: ['West End', 'Gold Coast', 'Bay Farm Island', 'Harbor Bay', 'Fernside', 'East End', 'Alameda Point', 'Marina Village'],
    faqs: [
      { q: 'Do you serve all areas of Alameda island?', a: 'Yes — we cover the entire island including West End, Gold Coast, Bay Farm Island, Harbor Bay, and Alameda Point.' },
      { q: 'How long does it take to reach Alameda from Oakland?', a: 'We can typically reach Alameda within 30–35 minutes via the Posey or Webster tubes. We keep this in mind for emergency dispatching.' },
      { q: 'Do you handle sewer line issues in Alameda?', a: 'Yes. We specialize in sewer line repair and replacement for Alameda\'s older homes, many of which have aging clay or cast iron sewer laterals.' },
    ],
  },

  'san-leandro': {
    city: 'San Leandro',
    slug: 'san-leandro',
    state: 'CA',
    zip: '94577',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1600&q=80',
    metaTitle: 'Plumber in San Leandro CA | Same-Day Plumbing | (510) 555-0199',
    metaDesc: 'Professional plumbing services in San Leandro, CA. Emergency plumbing, drain cleaning, water heater repair. Same-day service. Call (510) 555-0199.',
    headline: 'Reliable Plumbing Services in San Leandro, CA',
    subtitle: 'San Leandro\'s go-to plumbing team — fast response times, fair pricing, and quality work backed by warranty.',
    about: 'Oakland Plumbing Experts serves all of San Leandro, CA with the same fast response and quality workmanship that Oakland residents have trusted for over 15 years. From San Leandro\'s residential neighborhoods to its industrial and commercial corridors, our licensed plumbers handle everything from routine drain cleaning to complex sewer line replacements. We\'re familiar with San Leandro\'s local plumbing codes and permit requirements.',
    neighborhoods: ['Downtown San Leandro', 'Estudillo Estates', 'Washington Manor', 'Bal Harbor', 'Broadmoor', 'Davis Estates', 'Floresta Gardens', 'Manor'],
    faqs: [
      { q: 'Do you provide emergency plumbing in San Leandro?', a: 'Yes. We offer 24/7 emergency plumbing service throughout San Leandro with typical response times of 30–45 minutes.' },
      { q: 'Do you serve commercial properties in San Leandro?', a: 'Absolutely. We handle commercial plumbing for San Leandro businesses, restaurants, and industrial properties, including after-hours emergency service.' },
      { q: 'Are you familiar with San Leandro plumbing codes?', a: 'Yes. Our plumbers are fully licensed in California and familiar with San Leandro\'s specific plumbing codes and permit requirements.' },
    ],
  },

  emeryville: {
    city: 'Emeryville',
    slug: 'emeryville',
    state: 'CA',
    zip: '94608',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600&q=80',
    metaTitle: 'Plumber in Emeryville CA | Commercial & Residential | (510) 555-0199',
    metaDesc: 'Expert plumbing services in Emeryville, CA. Residential and commercial plumbing, emergency service available 24/7. Call (510) 555-0199.',
    headline: 'Expert Plumbing Services in Emeryville, CA',
    subtitle: 'Residential and commercial plumbing for Emeryville — right next door to Oakland with the fastest response times in the East Bay.',
    about: 'Emeryville\'s unique mix of modern condos, converted lofts, and commercial developments requires a plumber who understands both residential and commercial plumbing systems. Oakland Plumbing Experts is just minutes from Emeryville and serves the entire city — from the Bay Street shopping area to the tech campuses and residential towers along the waterfront. Our commercial plumbing team is especially experienced with the high-rise and mixed-use buildings common in Emeryville.',
    neighborhoods: ['Bay Street', 'Watergate', 'Emery Bay', 'Christie Ave Corridor', 'Powell Street', 'Sherwin Williams District', 'North Hollis', 'South Bayfront'],
    faqs: [
      { q: 'Do you handle commercial plumbing in Emeryville?', a: 'Yes. We specialize in commercial plumbing for Emeryville\'s offices, retail spaces, restaurants, and mixed-use developments.' },
      { q: 'How fast can you reach Emeryville?', a: 'Emeryville is right next to Oakland — we can typically arrive within 20–30 minutes for emergencies.' },
      { q: 'Do you work on high-rise and condo buildings in Emeryville?', a: 'Yes. Our commercial plumbing team has extensive experience with multi-story residential and commercial buildings, including high-rise plumbing systems.' },
    ],
  },
}
