export const servicesData = {
  'emergency-plumbing': {
    title: 'Emergency Plumbing Services in Oakland, CA',
    metaTitle: 'Emergency Plumber Oakland CA | 30-Min Response | (510) 555-0199',
    metaDesc: 'Oakland emergency plumber available 24/7. Burst pipes, flooding, gas leaks — we arrive in 30 minutes. Licensed & insured. Call (510) 555-0199.',
    icon: '🚨',
    // Flooded floor / water emergency
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1600&q=80',
    subtitle: 'Burst pipes, flooding, or any plumbing crisis — our licensed Oakland plumbers arrive in 30 minutes or less, any time of day or night.',
    description: 'When a plumbing emergency strikes, every minute counts. Oakland Plumbing Experts provides rapid-response emergency plumbing services throughout Oakland and the East Bay. Our fully-stocked trucks and experienced plumbers are ready to handle any crisis — from burst pipes and severe flooding to gas line emergencies and sewer backups. We operate 24 hours a day, 7 days a week, 365 days a year with no extra charge for nights or weekends.',
    included: [
      'Burst pipe repair and emergency shutoff',
      'Flooding and water damage mitigation',
      'Sewer backup and overflow cleanup',
      'Gas line emergency response',
      'Water heater failure and replacement',
      'Frozen pipe thawing and repair',
      'Toilet overflow and sewage backup',
      '24/7 availability including holidays',
    ],
    faqs: [
      { q: 'How quickly can you respond to a plumbing emergency in Oakland?', a: 'We guarantee arrival within 30 minutes for emergencies in Oakland. Our trucks are stationed throughout the East Bay for maximum coverage.' },
      { q: 'Do you charge extra for emergency calls at night or on weekends?', a: 'No. We charge the same rates 24/7 — no emergency surcharges, no weekend fees, no holiday markups.' },
      { q: 'What should I do while waiting for the emergency plumber?', a: 'Locate and shut off your main water valve to stop flooding. For gas leaks, evacuate and call 911 first, then call us. We\'ll guide you through steps over the phone.' },
    ],
    defaultService: 'Emergency Plumbing',
  },

  'drain-cleaning': {
    title: 'Professional Drain Cleaning Services in Oakland, CA',
    metaTitle: 'Drain Cleaning Oakland CA | Same-Day Service | (510) 555-0199',
    metaDesc: 'Expert drain cleaning in Oakland, CA. Clogged drains cleared fast with hydro-jetting. Same-day service available. Call (510) 555-0199.',
    icon: '🚿',
    // Kitchen sink / drain close-up
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=1600&q=80',
    subtitle: 'Slow or clogged drains cleared fast using professional hydro-jetting and drain snake equipment. Same-day service available throughout Oakland.',
    description: 'Clogged drains are one of the most common plumbing problems in Oakland homes and businesses. Oakland Plumbing Experts uses professional-grade hydro-jetting equipment and motorized drain snakes to clear even the most stubborn blockages. Unlike store-bought chemicals that damage pipes, our methods are safe, effective, and long-lasting. We clear kitchen drains, bathroom drains, floor drains, and main sewer lines.',
    included: [
      'Kitchen sink and garbage disposal clogs',
      'Bathroom sink, tub, and shower drains',
      'Toilet clogs and blockages',
      'Floor drain cleaning',
      'Main sewer line clearing',
      'Hydro-jetting for severe buildup',
      'Video camera drain inspection',
      'Preventive drain maintenance',
    ],
    faqs: [
      { q: 'How do I know if I need professional drain cleaning?', a: 'Signs include slow draining, gurgling sounds, recurring clogs, or foul odors from drains. If multiple drains are slow simultaneously, you likely have a main line issue.' },
      { q: 'Is hydro-jetting safe for my pipes?', a: 'Yes. Hydro-jetting is safe for most pipe materials including PVC, copper, and cast iron when performed by a professional. We assess your pipes before recommending the right method.' },
      { q: 'How long does drain cleaning take?', a: 'Most drain cleaning jobs take 1–2 hours. Main sewer line clearing may take 2–4 hours depending on the severity of the blockage.' },
    ],
    defaultService: 'Drain Cleaning',
  },

  'water-heater-repair': {
    title: 'Water Heater Repair & Replacement in Oakland, CA',
    metaTitle: 'Water Heater Repair Oakland CA | Same-Day | (510) 555-0199',
    metaDesc: 'Water heater repair and replacement in Oakland, CA. All brands serviced. Tankless installation available. Same-day service. Call (510) 555-0199.',
    icon: '🔥',
    // Water heater tank unit
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80',
    subtitle: 'No hot water? Our Oakland plumbers repair and replace all water heater brands — traditional tank and tankless — with same-day service.',
    description: 'A broken water heater disrupts your entire household. Oakland Plumbing Experts services and replaces all major water heater brands including Rheem, Bradford White, A.O. Smith, and Navien. Whether you have a traditional tank water heater or a modern tankless system, our certified plumbers diagnose the problem fast and provide upfront pricing before any work begins. We also offer energy-efficient tankless upgrades that can reduce your energy bills by up to 40%.',
    included: [
      'Water heater diagnosis and repair',
      'Tank water heater replacement',
      'Tankless water heater installation',
      'Anode rod replacement',
      'Thermostat and heating element repair',
      'Pressure relief valve replacement',
      'Water heater flushing and maintenance',
      'All major brands serviced',
    ],
    faqs: [
      { q: 'How long does a water heater last?', a: 'Traditional tank water heaters last 8–12 years. Tankless units last 15–20 years with proper maintenance. If yours is over 10 years old and failing, replacement is often more cost-effective than repair.' },
      { q: 'Should I repair or replace my water heater?', a: 'If your unit is under 8 years old and the repair cost is less than 50% of replacement cost, repair makes sense. Older units or those with major failures are better replaced.' },
      { q: 'How much does water heater replacement cost in Oakland?', a: 'Tank water heater replacement typically ranges from $800–$1,500 installed. Tankless units range from $1,500–$3,000 installed. We provide free estimates before any work.' },
    ],
    defaultService: 'Water Heater Repair',
  },

  'leak-detection': {
    title: 'Professional Leak Detection Services in Oakland, CA',
    metaTitle: 'Leak Detection Oakland CA | Non-Invasive | (510) 555-0199',
    metaDesc: 'Advanced leak detection in Oakland, CA. Find hidden water leaks without tearing up walls or floors. Licensed plumbers. Call (510) 555-0199.',
    icon: '🔍',
    // Water dripping / pipe leak
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1600&q=80',
    subtitle: 'Advanced non-invasive leak detection technology to find hidden water leaks before they cause thousands in damage to your Oakland home.',
    description: 'Hidden water leaks can cause massive structural damage, mold growth, and skyrocketing water bills before you even know they exist. Oakland Plumbing Experts uses state-of-the-art acoustic leak detection, thermal imaging, and pressure testing to pinpoint leaks behind walls, under slabs, and underground — without unnecessary demolition. Early detection saves Oakland homeowners thousands in repair costs.',
    included: [
      'Acoustic leak detection technology',
      'Thermal imaging camera inspection',
      'Slab leak detection and repair',
      'Underground pipe leak location',
      'Pool and spa leak detection',
      'Water meter leak testing',
      'Pressure testing for hidden leaks',
      'Full leak repair after detection',
    ],
    faqs: [
      { q: 'How do I know if I have a hidden water leak?', a: 'Warning signs include unexplained high water bills, damp spots on walls or floors, mold or mildew smell, low water pressure, or the sound of running water when all fixtures are off.' },
      { q: 'Can you find leaks without breaking walls?', a: 'Yes. Our non-invasive technology locates most leaks without any demolition. We only open walls or floors when absolutely necessary for repair, and we minimize the affected area.' },
      { q: 'How much does leak detection cost in Oakland?', a: 'Leak detection services start at $150–$300 depending on the type and complexity. This cost is often offset by the water savings and damage prevention from finding the leak early.' },
    ],
    defaultService: 'Leak Detection',
  },

  'sewer-line-repair': {
    title: 'Sewer Line Repair & Replacement in Oakland, CA',
    metaTitle: 'Sewer Line Repair Oakland CA | Trenchless | (510) 555-0199',
    metaDesc: 'Sewer line repair and replacement in Oakland, CA. Trenchless technology available. No-dig solutions. Licensed plumbers. Call (510) 555-0199.',
    icon: '🏗️',
    // Underground pipe / excavation work
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&q=80',
    subtitle: 'Trenchless sewer line repair and replacement in Oakland — fix your sewer without destroying your yard. Fast, affordable, and minimally invasive.',
    description: 'Sewer line problems are among the most serious plumbing issues a homeowner can face. Oakland Plumbing Experts specializes in trenchless sewer repair and replacement, allowing us to fix or replace your sewer line with minimal disruption to your landscaping, driveway, or property. We use video camera inspection to diagnose the exact problem before recommending the most cost-effective solution.',
    included: [
      'Video camera sewer line inspection',
      'Trenchless pipe lining (CIPP)',
      'Trenchless pipe bursting',
      'Traditional sewer line excavation',
      'Root intrusion removal',
      'Sewer line cleaning and jetting',
      'Sewer line replacement',
      'City connection and permits',
    ],
    faqs: [
      { q: 'What causes sewer line damage in Oakland?', a: 'Common causes include tree root intrusion (very common in Oakland\'s older neighborhoods), pipe corrosion, ground shifting, grease buildup, and aging clay or cast iron pipes.' },
      { q: 'What is trenchless sewer repair?', a: 'Trenchless methods repair or replace your sewer line through small access points rather than digging a trench the entire length of the pipe. This saves your yard, driveway, and landscaping.' },
      { q: 'How long does sewer line repair take?', a: 'Trenchless repairs typically take 1–2 days. Traditional excavation may take 2–5 days depending on the length and depth of the line.' },
    ],
    defaultService: 'Sewer Line Repair',
  },

  'pipe-repair': {
    title: 'Pipe Repair & Replacement Services in Oakland, CA',
    metaTitle: 'Pipe Repair Oakland CA | Burst Pipes | (510) 555-0199',
    metaDesc: 'Expert pipe repair and replacement in Oakland, CA. Burst pipes, corroded pipes, repiping services. Licensed plumbers. Call (510) 555-0199.',
    icon: '🔩',
    // Copper / metal pipes close-up
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1600&q=80',
    subtitle: 'Cracked, corroded, or burst pipes repaired fast by Oakland\'s licensed plumbers. From single pipe repairs to whole-home repiping.',
    description: 'Damaged pipes can cause water damage, mold, and structural issues if not addressed quickly. Oakland Plumbing Experts handles everything from single pipe repairs to complete whole-home repiping projects. Many Oakland homes have aging galvanized steel or copper pipes that are prone to corrosion and failure. We assess your entire plumbing system and recommend the most cost-effective solution, whether that\'s a targeted repair or a full repipe with modern PEX or copper.',
    included: [
      'Burst and cracked pipe repair',
      'Corroded pipe replacement',
      'Whole-home repiping (PEX/copper)',
      'Galvanized pipe replacement',
      'Water pressure issues',
      'Pipe insulation and freeze protection',
      'Under-slab pipe repair',
      'Commercial pipe repair',
    ],
    faqs: [
      { q: 'How do I know if my pipes need replacing?', a: 'Signs include discolored water, low water pressure throughout the home, frequent leaks, visible corrosion, or pipes over 50 years old. Galvanized steel pipes in older Oakland homes often need full replacement.' },
      { q: 'What is repiping and when is it necessary?', a: 'Repiping replaces all or most of your home\'s water supply pipes. It\'s recommended when pipes are severely corroded, frequently leaking, or made of outdated materials like galvanized steel or polybutylene.' },
      { q: 'How long does whole-home repiping take?', a: 'Most whole-home repipes take 2–4 days depending on home size. We minimize disruption and restore water service each evening so you\'re not without water overnight.' },
    ],
    defaultService: 'Pipe Repair',
  },

  'toilet-repair': {
    title: 'Toilet Repair & Replacement Services in Oakland, CA',
    metaTitle: 'Toilet Repair Oakland CA | Same-Day Service | (510) 555-0199',
    metaDesc: 'Toilet repair and replacement in Oakland, CA. Running toilets, clogs, leaks, and full replacements. Same-day service. Call (510) 555-0199.',
    icon: '🚽',
    // Clean modern bathroom / toilet
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1600&q=80',
    subtitle: 'Running toilets, persistent clogs, leaks, or full replacements — Oakland\'s trusted plumbers fix all toilet problems fast and affordably.',
    description: 'A malfunctioning toilet is more than an inconvenience — a running toilet can waste up to 200 gallons of water per day, costing you hundreds on your water bill. Oakland Plumbing Experts repairs and replaces all toilet brands and models. From simple flapper replacements to full toilet installations, our plumbers arrive with all necessary parts to complete most repairs in a single visit.',
    included: [
      'Running toilet repair',
      'Toilet clog removal',
      'Wax ring and seal replacement',
      'Fill valve and flapper replacement',
      'Toilet tank repair',
      'Toilet leak repair (base and tank)',
      'Full toilet replacement and installation',
      'Low-flow and water-saving upgrades',
    ],
    faqs: [
      { q: 'Why is my toilet running constantly?', a: 'A constantly running toilet is usually caused by a worn flapper, faulty fill valve, or float set too high. These are inexpensive repairs that our plumbers can fix in under an hour.' },
      { q: 'When should I replace vs. repair my toilet?', a: 'Repair if the toilet is under 15 years old and the issue is minor. Consider replacement if it\'s frequently clogging, cracked, or over 20 years old — newer models are also significantly more water-efficient.' },
      { q: 'How much does toilet repair cost in Oakland?', a: 'Simple repairs like flapper or fill valve replacement start at $75–$150. Full toilet replacement with installation typically ranges from $300–$600 depending on the fixture chosen.' },
    ],
    defaultService: 'Toilet Repair',
  },

  'commercial-plumbing': {
    title: 'Commercial Plumbing Services in Oakland, CA',
    metaTitle: 'Commercial Plumber Oakland CA | Business Plumbing | (510) 555-0199',
    metaDesc: 'Commercial plumbing services in Oakland, CA. Restaurants, offices, retail, and multi-unit buildings. Licensed & insured. Call (510) 555-0199.',
    icon: '🏢',
    // Commercial building / office exterior
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80',
    subtitle: 'Full-service commercial plumbing for Oakland businesses, restaurants, offices, and multi-unit properties. Minimal downtime, maximum reliability.',
    description: 'Oakland Plumbing Experts provides comprehensive commercial plumbing services for businesses of all sizes throughout Oakland and the East Bay. We understand that plumbing downtime costs your business money, which is why we offer flexible scheduling, rapid response, and efficient service to minimize disruption. From restaurants and retail to office buildings and multi-unit residential properties, our licensed commercial plumbers handle projects of any scale.',
    included: [
      'Commercial drain cleaning and jetting',
      'Grease trap installation and cleaning',
      'Backflow prevention and testing',
      'Commercial water heater service',
      'Multi-unit plumbing systems',
      'Restaurant and kitchen plumbing',
      'ADA-compliant fixture installation',
      'Preventive maintenance contracts',
    ],
    faqs: [
      { q: 'Do you offer after-hours commercial plumbing service?', a: 'Yes. We offer 24/7 emergency commercial plumbing service for Oakland businesses. We can also schedule non-emergency work during off-hours to minimize disruption to your operations.' },
      { q: 'Can you handle large commercial plumbing projects?', a: 'Absolutely. We handle everything from single-fixture repairs to full commercial buildouts and multi-unit residential plumbing systems. We\'re licensed for all commercial work in California.' },
      { q: 'Do you offer maintenance contracts for businesses?', a: 'Yes. We offer customized preventive maintenance contracts for Oakland businesses that include regular inspections, drain cleaning, and priority emergency response.' },
    ],
    defaultService: 'Commercial Plumbing',
  },
}
